pretrain_l_m: bert-large
# network
batch: 16
epoch: 200
bilstm_layers: 1
word_dim: 100
lstm_dim: 128
out_dim: 128
type_dim: 20
coref_dim: 20
dist_dim: 20
drop_i: 0.2 # 0.5
drop_o: 0.2 # 0.3
lr: 0.001
bert_lr: 0.00001
lr_decay_rate: 0.1
lr_decay_step: 10000
gc: 10
reg: 0.000
opt: adam
loss_weight: false
patience: 10
unk_w_prob: 1.0
min_w_freq: 1
init_train_epochs: 5
NA_NUM: 1.0
mlp_layers: 2
adj_is_sparse: False

# data based
dep_adj_no_split: true
train_data: ../data/DocPRE/processed/train_annotated.data
test_data: ../data/DocPRE/processed/dev.data
embeds: true
folder: ../results/docred-dev
save_pred: dev

# options (chosen from parse input otherwise false)
lowercase: true
plot: true
show_class: false
param_avg: false
early_stop: true
save_model: true
types: true
context: true  # MM
dist: true  # MM SS
finaldist: false  # EE  # it is good
freeze_words: true
re_train: false

# extra
seed: 0
shuffle_data: true
label2ignore: NA
primary_metric: micro_f
edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
walks_iter: 3
